import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from "../components/Banner";
const inter = Inter({ subsets: ['latin'] })
import Button from '@/components/Button';
import {useRouter} from 'next/router';
import Card from "../components/Card";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>My Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <div className="body-cotainer">

        
          <Banner isLoginBtnReq={true} className="h-[70vh]">

            <div className=" relative max-width">
              <div className="text-button-container flex flex-row mt-4 justify-evenly md:flex-col md:justify-start md:ml-14 lg:ml-48">

                <h1 className="text-white text-2xl lg:text-4xl xl:text-6xl my-auto md:mt-24 ">
                  Welcome to <br/><span className="font-bold">My<span className="text-secodaryBlue">Jobs</span></span>
                </h1>
                <Button btnType="button" className="my-auto md:mt-10 md:mb-8 lg:mt-10 lg:mb-16 " onClick={() => {
                  router.push("/signup");
                }}><span className="font-medium ">Get Started</span></Button>
              </div>

              <Image src="/meeting.webp" priority={true} alt="Three people in meeting" width={320} height={1} className="mt-8 drop-shadow-lg	mx-auto md:absolute md:bottom-8 lg:-bottom-3 xl:-bottom-16 right-40  md:w-[350px]  lg:w-[450px]  xl:w-[570px] "/>

            </div>

          </Banner>
      
        <div className="details-container mx-10 bg-veryLightBlue max-width">
          <div className="details flex flex-col justify-center pt-36 ">
            <div className="mx-auto space-y-20">
            <h3 className="text-lg  md:text-xl text-secondary capitalize font-bold">why us</h3>
            <div className="card-container mt-10  flex flex-col gap-y-3 md:gap-x-3 md:flex-row lg:gap-x-6 xl:gap-x-8">
              <Card>
                <p className="font-medium">Get more <br/>visibility</p>
              </Card>
              <Card>
                <p className="font-medium">Organize your <br/>candidates</p>
              </Card>
              <Card>
                <p className="font-medium">Verify their <br/>abilities</p>
              </Card>
            </div>

            

              <h3 className="text-xl text-secondary capitalize font-bold ">companies who trust us</h3>
              <div className="">

                <div className="logo-cont1 mt-10  flex flex-wrap md:justify-between ">

                <Image src="/logos/solaytic@2x.png" alt="goldline" width={90} height={40} className="lg:w-[125px]"/>
                <Image src="/logos/kanba@2x.png" alt="goldline" width={90} height={1} className="lg:w-[144px]"/>
                <Image src="/logos/lighting@2x.png" alt="goldline" width={90} height={40} className="lg:w-[124px]"/>
                <Image src="/logos/ztos@2x.png" alt="goldline" width={90} height={40} className="lg:w-[100px]"/>  
                <Image src="/logos/kanba@2x.png" alt="goldline" width={90} height={40} className="lg:w-[144px]"/>

                </div>
                <div className="logo-cont2 mt-14  flex flex-wrap md:justify-evenly mx-26">
                  <Image src="/logos/goldline@2x.png" alt="goldline" width={90} height={40} className="lg:w-[172px]"/>
                  <Image src="/logos/ideaa@2x.png" alt="goldline" width={90} height={40} className="lg:w-[118px]"/>
                  <Image src="/logos/liva@2x.png" alt="goldline" width={90} height={40} className="lg:w-[100px]"/>
                  <Image src="/logos/velocity-9@2x.png" alt="goldline" width={90} height={40} className="lg:w-[156px]"/>
                </div>  
              </div>
                
            </div>

          </div>
        </div>

      </div>
    </>
  )
}
